### ISSUE TITLE
The application stucks on the black screen and not responding.

### ISSUE THREAD

**Issue by sargoon** [wownero/wownerujo#24]
Hi there @wownero
The application stucks on the black screen. My device's back button does not work and the application not responding.

App version: 2.6.1.1 (latest)
My Android version: 9.0

**Record of the Bug**
![PoshSleepyInvisiblerail-size_restricted](https://user-images.githubusercontent.com/34961616/60775421-9a8b5900-a12b-11e9-83de-bf0125d6ed5c.gif)

**Comment by sargoon** [comment]
Are you there @wownero?

**Comment by wowario** [comment]
@sargoon I assume whatever problem you were having has been fixed with latest version. If not, reopen issue.
