### ISSUE TITLE
10% of wownerujo users run their own bank :p

### ISSUE THREAD

**Issue by fuwa0529** [wownero/wownerujo#25]
![Screenshot_2019-08-11_07-30-30](https://user-images.githubusercontent.com/40521440/62827806-3536f600-bc0a-11e9-807e-2d6c938617ce.png)

**Comment by fuwa0529** [comment]
20% now, but this app is pretty ded (java's day is counted). At lease people have some experience  working with a real node.

**Comment by ACwiner** [comment]
Tell me please, in the wallet wownerujo I can not send a transaction more 245 wownero , what could be the reason?( thanks in advance)
