### ISSUE TITLE
Cannot transfer to exchange

### ISSUE THREAD

**Issue by mild7seven** [wownero/wownerujo#29]
Has someone succeed withdraw to exchange account for wownero coin.

I got problem, where it cannot transfer to exchange like tradeogre.
![WhatsApp Image 2019-12-03 at 5 04 53 PM](https://user-images.githubusercontent.com/58162778/70041336-90448c80-15ef-11ea-8def-8696208bf2d6.jpeg)

**Comment by fuwa0529** [comment]
Are you running the latest version which should be v2.7.0.0 and connecting to the latest daemon which is v0.7.0.0?

**Comment by mild7seven** [comment]
I've tried again with wallet latest version v2.7.0.0 and daemon v0.7.0.0 block 166810. still facing an error.

**Comment by mild7seven** [comment]
Ok it's working, i forgot to change the node on the wallet.
